### ISSUE TITLE
in python 2.7 and 3.5

### ISSUE THREAD

**Issue by dialogchat** [XifengGuo/CapsNet-Pytorch#1]
c = F.softmax(b, dim=1)
TypeError: softmax() got an unexpected keyword argument 'dim'

**Comment by dialogchat** [comment]
fixed as follows:
changed line 67 in capsulelayers.py to 
c = F.softmax(b)

a test training shows this output. looks like increasing acc. and decreas. loss, so OK?!

==> Epoch 00: loss=0.12860, val_loss=0.03752, val_acc=0.9876, time=416s
best val_acc increased to 0.9876
==> Epoch 01: loss=0.04457, val_loss=0.03283, val_acc=0.9916, time=416s
best val_acc increased to 0.9916
==> Epoch 02: loss=0.03801, val_loss=0.02926, val_acc=0.9936, time=417s
best val_acc increased to 0.9936

**Comment by Sundrops** [comment]
update your pytorch. Make it latest.
